### ISSUE TITLE
writers.las X scale error when running file twice in ipython after importing matplotlib

### ISSUE THREAD

**Issue by sedot42** [PDAL/python#15]
Hi, I spent the last two hours debugging a very strange error. The following script with [this testfile](https://github.com/PDAL/python/files/2557223/testfile.zip) causes an error when it is run twice from within ipython (eg for debugging purposes). It only occurs when matplotlib.pyplot is imported.
```python
import matplotlib.pyplot
import pdal

pipeline = pdal.Pipeline("""
{
"pipeline":[
    {
        "type":"readers.las",
        "filename":"./testfile/testfile_in.laz"
    },
    {
        "type": "writers.las",
        "filename": "180417_133121.las",
        "scale_x": 0.0001
    }
]
}
""")

pipeline.validate()
pipeline.execute()
```
Steps to reproduce:
- run `ipython`
- run script with `%run bugreport.py`
- run script again as above

Result:
```
pdal/libpdalpython.pyx in pdal.libpdalpython.PyPipeline.execute()

RuntimeError: writers.las: X scale of 0.0 is invalid!
```

**Comment by hobu** [comment]
> when it is run twice 

I would suspect there is an error in the Python extension and the message you are receiving is a red herring. I just pushed 2.1.0rc2 yesterday. Can you please try that version (I'm not confident it does anything different, but you'll confirm you're using the latest).

https://pypi.org/project/PDAL/2.1.0rc2/

Howard

**Comment by sedot42** [comment]
I built via `git clone PDAL/python; python setup.py build; python setup.py install`. State of the repository was commit bb68cb0. Now I'm on `pip install --user pdal==2.1.0rc2` and the bug still exists.

**Comment by hobu** [comment]
Can you replicate this with a LAS file or some other data type besides RXP? I have no way to replicate a scenario with that.

**Comment by sedot42** [comment]
Yes, try [this file](https://github.com/PDAL/python/files/2557223/testfile.zip).

**Comment by hobu** [comment]
The script succeeds for me with PDAL 1.8 and 74005676ba8fdbf03869bd8e0a488c920c81e177 of the Python extension

**Comment by hobu** [comment]
Please make a conda requirements.txt file and script that demonstrates your issue. As it is now, I have to pat my head one way, rub my belly the other, and stand on a special square to make this bug happen 😄. I believe you, but I can't spend a bunch of time investigating the mystery.

**Comment by sedot42** [comment]
I cannot reproduce the issue using a script. Not even when running iPython magic via script. Obscurely enough, it only occurs when manually using the iPython magic command `%run` twice in an interactive session in combination with matplotlib. As it stands now, I am just avoiding interactive debugging while plotting. Maybe it's better to close this / save the time until more people are affected.
