### ISSUE TITLE
Pdalargs do not get updated if multiple pipelines are run in one script

### ISSUE THREAD

**Issue by ahalota** [PDAL/python#40]
Pdalargs do not get updated if multiple pipelines are run in one script.

```
def changeArgs():
    '''A test function see if arguments get changed with pdal filters.python
    '''
    
    pipe1 = {"pipeline" : [
        {"type" : "filters.python",
         "script" : "pdal_filters.py",
         "function" : "printArgs",
         "module" : "anything",
         "pdalargs" : "{\"name\" : \"pipe1\"}"}]}

    pipe2 = {"pipeline" : [
        {"type" : "filters.python",
         "script" : "pdal_filters.py",
         "function" : "printArgs",
         "module" : "anything",
         "pdalargs" : "{\"name\" : \"pipe1\"}"}]}
    
    pipeline = pdal.Pipeline(json.dumps(pipe1))
    pipeline.validate() #check if our JSON and options were good
    pipeline.execute()

    pipeline = pdal.Pipeline(json.dumps(pipe2))
    pipeline.validate() #check if our JSON and options were good
    pipeline.execute()
    
    return
```

pdal_filters.py:
```
def printArgs(ins,outs):
    '''To test if args even change if run multiple times!'''
    print(pdalargs)
    return True
```

Expected output:
```
{'name': 'pipe1'}
{'name': 'pipe2'}
```

Actual output:
```
{'name': 'pipe1'}
{'name': 'pipe1'}
```

**Comment by ahalota** [comment]
I found a workaround. This code below adds a step to delete pdalargs after completion, which allows it to be reset. 

I'm not sure where the issue is in the actual pdal code as I haven't looked into it yet, but this should definitely be default behavior!

```
def changeArgs():
    '''A test function see if arguments get changed with pdal filters.python    
    '''

    namez = ['apple1','banana2','chicken3']
    pipez = []
    print('changeArgs():')
    
    for n in namez:            
        pipe = {"pipeline" : [
            {   "type" : "readers.las",
                "filename" : utmIn
            },
            {   
                "type" : "filters.python",
                "script" : "pdal_filters.py",
                 "function" : "printArgs",
                 "module" : "anything",
                 "pdalargs" : "{\"namez\" : \"" + n + "\"}"
             },
             {   
                "type" : "filters.python",
                "script" : "pdal_filters.py",
                 "function" : "delArgs",
                 "module" : "anything",
             }

        ]}
                
        print('\t'+str(pipe['pipeline'][1]['pdalargs']))
        pipez.append(pipe)
    
    print('pipelines:')
    for p in pipez:     
        pipeline = pdal.Pipeline(json.dumps(p))
        pipeline.validate() #check if our JSON and options were good
        pipeline.execute()

        
    return
```

**pdal_filters.py**:
```
def printArgs(ins,outs):
    print('\t'+str(pdalargs))
    return True

def delArgs(ins,outs):
    global pdalargs
    del pdalargs
    return True
```

**Output:**
```
changeArgs():
	{"namez" : "apple1"}
	{"namez" : "banana2"}
	{"namez" : "chicken3"}
pipelines:
	{'namez': 'apple1'}
	{'namez': 'banana2'}
	{'namez': 'chicken3'}

```

**Comment by abellgithub** [comment]
I have re-worked the PDAL python filter.  I believe that it addresses this issue.  If you would like to build this branch: https://github.com/PDAL/PDAL/tree/issue-2788 you can test.

**Comment by abellgithub** [comment]
Fixed by https://github.com/PDAL/PDAL/pull/2795

**Comment by ahalota** [comment]
I updated python-pdal today and am still seeing the same issue. It doesn't appear that it was fixed?

**Comment by abellgithub** [comment]
This bug was not an extension bug, but a problem with the actual PDAL python filter.  In order to see the change, you would need to build PDAL (or at least the python filter) from source, as we have not released PDAL since the change was made.

I believe that you can work around this by changing the module name in the python scripts that you run.

**Comment by ahalota** [comment]
I see. A bit intimidating! I will stick with my silly fix for now then, since it seems to work.

**Comment by abellgithub** [comment]
A few problems can be worked around by simply using a separate module for each pipeline invocation.
